version: '3'
services:
  test-api:
    image: test-api
    container_name: test-api
    env_file: ./.env

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped
    ports:
      - 3219:8080

networks:
  default:
    external:
      name: dev
